# basic options
title: Stichting Solaris Onderzoek en Ontwikkeling
author: Natalia Bielczyk
email: solaris.nijmegen@gmail.com
description: a foundation
twitter_username: solaris_oo
github_username: stichting-solaris

# Build settings
markdown: kramdown
# Supported themes are available here: https://pages.github.com/themes/
theme: cayman
